{% set name = "mosaic-clustering" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mosaic-clustering-{{ version }}.tar.gz
  sha256: 27f8b7cbf1109b36c7728c8acaf48b60e8f42f4eb44b7bbdd6afce268b798544

build:
  noarch: python
  entry_points:
    - mosaic = mosaic.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - beartype >=0.10.4
    - click >=7.0.0
    - igraph
    - leidenalg >=0.8.0
    - numpy >=1.21.0
    - pandas
    - prettypyplot
    - python >=3.8
    - scikit-learn
    - scikit-learn-extra
    - scipy
    - typing-extensions >=3.9.0
    - umap-learn

test:
  imports:
    - mosaic
  commands:
    - pip check
    - mosaic --help
  requires:
    - pip

about:
  home: https://github.com/moldyn/MoSAIC
  summary: Correlation based feature selection for molecular dynamics data
  license: MIT
  license_file: LICENSE
  doc_url: https://moldyn.github.io/MoSAIC/

extra:
  recipe-maintainers:
    - braniii
